name: C++ CI with Google Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake lcov libgtest-dev

    - name: Build and Run Tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure

    - name: Generate Coverage Report
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Upload Coverage Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: build/coverage.info
