    - name: Build the Project
      run: |
        # Check if the build directory exists and create it if not
        if [ ! -d "build" ]; then
          mkdir build
        fi
        cd build
        cmake ..
        make
